development:
  adapter: postgresql
  encoding: unicode
  database: quasar_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: quasar_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: quasar_production
  pool: 5
  username: postgres
  password:
